name: Build image

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/build-image.yml'
      - 'image/**'
      - '!image/repo-snapshot/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build image
    outputs:
      # key에는 변수를 쓸 수 없어 하드코딩됨 식별자 사용
      metadata-linux-amd64: ${{ steps.collect-output.outputs.metadata-linux-amd64 }}
      metadata-linux-arm64: ${{ steps.collect-output.outputs.metadata-linux-arm64 }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # platform_id: For GH actions output discriminator.
          - platform_id: linux-amd64
            runner: ubuntu-24.04
          - platform_id: linux-arm64
            runner: ubuntu-24.04-arm

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #  v5.0.0
        with:
          # Reproduce the exact commit hash value
          fetch-depth: 0

      - name: Collect Git environment
        id: git-info
        run: |
          echo "git_tree_id=$(git rev-parse HEAD^{tree})" >> "$GITHUB_OUTPUT"
          echo "git_ref_name_escaped=$(echo '${{ github.ref_name }}' | sed 's/[^A-Za-z0-9._-]/-/g')" >> "$GITHUB_OUTPUT"
          echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> "$GITHUB_ENV"

      - name: Setup Docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          # nightly: @see https://github.com/moby/buildkit/commit/fe65d5ff62506d0bccdcc4641fad1920903fcf55
          # > remotecache: fix inline cache used with multiple exporters
          driver-opts: >-
            image=docker.io/moby/buildkit:v0.26.0@sha256:93da6a53287490dd3b35952f73a109654ed9f260f2e6434db925125fa3ac6b2a
          buildkitd-flags: >-
            --oci-worker-snapshotter=stargz

      - name: Login to Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          annotations: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.licenses=

      - name: "Build image: stage0"
        id: build-stage0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: image/stage0/
          build-contexts: |
            repo-snapshot=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/almalinux-repo-snapshot:latest
            container-script=image/container-script
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage0/**') }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-cache.${{ matrix.platform_id }}.master
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage0/**') }},mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage0-build.${{ matrix.platform_id }}.${{ github.run_id }}
          outputs: type=registry,name-canonical=true,oci-mediatypes=true,oci-artifact=true,compression=estargz,store=false

      - name: "Build image: stage1"
        id: build-stage1
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: image/stage1/
          build-contexts: |
            repo-snapshot=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/almalinux-repo-snapshot:latest
            container-script=image/container-script
            stage0=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp@${{ steps.build-stage0.outputs.imageid }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage1/**') }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-cache.${{ matrix.platform_id }}.master
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage1/**') }},mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage1-build.${{ matrix.platform_id }}.${{ github.run_id }}
          outputs: type=registry,name-canonical=true,oci-mediatypes=true,oci-artifact=true,compression=estargz,store=false

      - name: "Build image: stage2"
        id: build-stage2
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: image/stage2/
          build-contexts: |
            repo-snapshot=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/almalinux-repo-snapshot:latest
            container-script=image/container-script
            stage1=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp@${{ steps.build-stage1.outputs.imageid }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage2/**') }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-cache.${{ matrix.platform_id }}.master
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage2/**') }},mode=max
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage2-build.${{ matrix.platform_id }}.${{ github.run_id }}
          outputs: type=registry,name-canonical=true,oci-mediatypes=true,oci-artifact=true,compression=estargz,store=false

      - name: "Build image: stage3"
        id: build-stage3
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: image/stage3/
          build-contexts: |
            repo-snapshot=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/almalinux-repo-snapshot:latest
            container-script=image/container-script
            stage2=docker-image://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp@${{ steps.build-stage2.outputs.imageid }}
          cache-from: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage3/**') }}
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-cache.${{ matrix.platform_id }}.master
          cache-to: |
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-cache.${{ matrix.platform_id }}.${{ steps.git-info.outputs.git_ref_name_escaped }},mode=max
            type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-cache.${{ matrix.platform_id }}.${{ hashFiles('image/stage3/**') }},mode=max
          #sbom: true
          provenance: true
          annotations: ${{ steps.docker-meta.outputs.annotations }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/tmp:stage3-build.${{ matrix.platform_id }}.${{ github.run_id }}
          outputs: type=registry,name-canonical=true,oci-mediatypes=true,oci-artifact=true,compression=estargz,store=false

      - name: Collect output
        id: collect-output
        run: |
          printf "metadata-%s=%s\n" '${{ matrix.platform_id }}' "$(base64 --wrap=0 <<< '${{ steps.build-stage3.outputs.metadata }}')" >> "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-latest
    needs:
      - build-image
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Retrieve build outputs
        run: |
          mkdir -p "${{ runner.temp }}/image-metadata"
          echo '${{ toJSON(needs.build-image.outputs) }}' | jq -r 'to_entries[] | "\(.key)\t\(.value)"' |
            while IFS=$'\t' read -r key b64data ; do
              base64 --decode <<< "$b64data" > "${{ runner.temp }}/image-metadata/${key}.json"
            done

      - name: Setup Docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=git-,format=long

      - name: Create manifest
        id: create-manifest
        run: |
          repo_image='${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
          build_id_tag='gha-${{ github.run_id }}'
          digests=( $(cd "${{ runner.temp }}/image-metadata" && cat metadata-*.json | jq -r '.["containerimage.digest"]') )

          set -x
          docker buildx imagetools create \
            --tag "${repo_image}:${build_id_tag}" \
            $(echo '${{ steps.docker-meta.outputs.tags }}' | sed 's/^/--tag /') \
            $(printf "${repo_image}/tmp@%s " "${digests[@]}") \
          ;

          docker buildx imagetools inspect "${repo_image}:${build_id_tag}"

          digest=$(docker buildx imagetools inspect --format '{{(.Manifest).Digest}}' "${repo_image}:${build_id_tag}")
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

      - name: Create attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.create-manifest.outputs.digest }}
          push-to-registry: true
