name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-image:
    name: Build image
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #  v5.0.0
        with:
          # Reproduce the exact commit hash value
          fetch-depth: 0

      - name: Gather SOURCE_DATE_EPOCH
        run: echo "SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Setup Docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Buildkit cache
        id: buildkit-cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: buildkit-cache
          key: buildkit-cache-${{ runner.arch }}

      - name: Inject Buildkit cache
        uses: reproducible-containers/buildkit-cache-dance@5b81f4d29dc8397a7d341dba3aeecc7ec54d6361 # v3.3.0
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: buildkit-cache
          dockerfile: .devcontainer/Dockerfile
          save-always: true

      - name: Build image - stage0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          SOURCE_DATE_EPOCH: ${{ env.COMMIT_TIMESTAMP }}
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile
          target: stage0

      - name: Build image - stage1
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          SOURCE_DATE_EPOCH: ${{ env.COMMIT_TIMESTAMP }}
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile
          target: stage1

      - name: Build image - final
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          SOURCE_DATE_EPOCH: ${{ env.COMMIT_TIMESTAMP }}
        with:
          context: .devcontainer/
          file: .devcontainer/Dockerfile
          sbom: true
          provenance: true
