name: CI

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/ci.yml'
      - 'image/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    name: Build image
    outputs:
      # key에는 변수를 쓸 수 없어 하드코딩됨 식별자 사용
      metadata-linux-amd64: ${{ steps.collect-output.outputs.metadata-linux-amd64 }}
      metadata-linux-arm64: ${{ steps.collect-output.outputs.metadata-linux-arm64 }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # platform_id: For GH actions output discriminator.
          - platform_id: linux-amd64
            runner: ubuntu-24.04
          - platform_id: linux-arm64
            runner: ubuntu-24.04-arm

    env:
      SOURCE_DATE_EPOCH: 0
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #  v5.0.0
        with:
          # Reproduce the exact commit hash value
          fetch-depth: 0

      - name: Setup Docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
        with:
          buildkitd-flags: >-
            --oci-worker-snapshotter=stargz

      - name: "Cache volume: dnf"
        id: cache-volume-dnf
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: buildkit-cache-dnf
          key: buildkit-cache-dnf-${{ runner.arch }}

      - name: "Inject Buildkit cache"
        uses: reproducible-containers/buildkit-cache-dance@5b81f4d29dc8397a7d341dba3aeecc7ec54d6361 # v3.3.0
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          save-always: true
          cache-map: >-
            {
              "buildkit-cache-dnf": {
                "target": "/var/cache/dnf",
                "id": "dnf"
              }
            }

      - name: Login to Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          annotations: |
            org.opencontainers.image.created={{commit_date 'YYYY-MM-DDTHH:mm:ss.SSS[Z]'}}
            org.opencontainers.image.licenses=

      - name: "Build image: stage0"
        id: build-stage0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: image/stage0/
          file: image/stage0/Dockerfile
          cache-from: type=gha,scope=stage0-${{ runner.arch }}
          cache-to: type=gha,scope=stage0-${{ runner.arch }},mode=max
          outputs: type=oci,dest=${{ runner.temp }}/stage0-image,tar=false,oci-mediatypes=true,compression=estargz,force-compression=true

      - name: "Build image: stage1"
        id: build-stage1
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: image/stage1/
          file: image/stage1/Dockerfile
          build-contexts: |
            stage0=oci-layout://${{ runner.temp }}/stage0-image
          cache-from: type=gha,scope=stage1-${{ runner.arch }}
          cache-to: type=gha,scope=stage1-${{ runner.arch }},mode=max
          outputs: type=oci,dest=${{ runner.temp }}/stage1-image,tar=false,oci-mediatypes=true,compression=estargz,force-compression=true

      - name: "Build image: stage2"
        id: build-stage2
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: image/stage2/
          file: image/stage2/Dockerfile
          build-contexts: |
            stage0=oci-layout://${{ runner.temp }}/stage0-image
            stage1=oci-layout://${{ runner.temp }}/stage1-image
          cache-from: type=gha,scope=stage2-${{ runner.arch }}
          cache-to: type=gha,scope=stage2-${{ runner.arch }},mode=max
          sbom: true
          provenance: true
          annotations: ${{ steps.docker-meta.outputs.annotations }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          outputs: type=image,push=true,push-by-digest=true,name-canonical=true,oci-mediatypes=true,oci-artifact=true,compression=estargz,force-compression=true

      - name: Collect output
        id: collect-output
        run: |
          printf "metadata-%s=%s\n" '${{ matrix.platform_id }}' "$(base64 --wrap=0 <<< '${{ steps.build-stage2.outputs.metadata }}')" >> "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-latest
    needs:
      - build-image
    permissions:
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Retrieve build outputs
        run: |
          mkdir -p "${{ runner.temp }}/image-metadata"
          echo '${{ toJSON(needs.build-image.outputs) }}' | jq -r 'to_entries[] | "\(.key)\t\(.value)"' |
            while IFS=$'\t' read -r key b64data ; do
              base64 --decode <<< "$b64data" > "${{ runner.temp }}/image-metadata/${key}.json"
            done

      - name: Setup Docker buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix=git-,format=long

      - name: Create manifest
        id: create-manifest
        run: |
          repo_image='${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
          build_id_tag='gha-${{ github.run_id }}'
          digests=( $(cd "${{ runner.temp }}/image-metadata" && cat metadata-*.json | jq -r '.["containerimage.digest"]') )

          set -x
          docker buildx imagetools create \
            --tag "${repo_image}:${build_id_tag}" \
            $(echo '${{ steps.docker-meta.outputs.tags }}' | sed 's/^/--tag /') \
            $(printf "$repo_image@%s " "${digests[@]}") \
          ;

          docker buildx imagetools inspect "${repo_image}:${build_id_tag}"

          digest=$(docker buildx imagetools inspect --format '{{(.Manifest).Digest}}' "${repo_image}:${build_id_tag}")
          echo "digest=$digest" >> "$GITHUB_OUTPUT"

      - name: Create attestation
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # v3.0.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.create-manifest.outputs.digest }}
          push-to-registry: true
